version: '2'
services:
  psycho-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/psycho/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=psycho
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
